
# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Frank Ohene-Darkoh
description: |
  Hi I'm Frank, and I'm a Data Analyst based in Ghana with strong foundations in Python (pandas) and SQL. I am passionate about using data to generate insights, contribute to research, and explore personal and industry projects.
  
  My collaborative approach makes me valuable to any team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#add8e6"> Portfolio </span>
location: "Accra, Ghana"
resume_url: "https://drive.google.com/file/d/1WERRlx7a8YKxnYr2vrMMsCQZpKStKbeu/view?usp=sharing"
avatar_image: 

#------------------------------- 
# Contact links
linkedln: "https://www.linkedin.com/in/frankohene-darkoh-44412222b" # Add your linkedln handle
github: "https://github.com/Ohenedarkoh" # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile"
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
