# Example _config.yml
title: Frank Ohene-Darkoh | Data Analyst Portfolio
logo : /assets/images/logo.png
email: ohenedarkohfrank@gmail.com
description: Data analyst with a strong foundation in Python (pandas) and SQL. I am passionate about using data to
 generate insights, contribute to research, and explore personal and industry projects. My collaborative
 approach makes me valuable to any team.
theme: jekyll-theme-midnight
github_username: Ohenedarkoh
linkedin_url: https://www.linkedin.com/in/frankohene-darkoh-44412222b
resume: https://drive.google.com/file/d/1WERRlx7a8YKxnYr2vrMMsCQZpKStKbeu/view?usp=sharing