# Example _config.yml
title: Frank Ohene-Darkoh | Data Analyst Portfolio
description: Projects and insights using Python, SQL, and Power BI.
theme: jekyll-theme-minimal 
github_username: Ohenedarkoh
linkedin_url: https://www.linkedin.com/in/frankohene-darkoh-44412222b
resume: https://drive.google.com/file/d/1WERRlx7a8YKxnYr2vrMMsCQZpKStKbeu/view?usp=sharing